/**
 * VOIR site data — sourced from:
 * Website Basic Brief.xlsx (TV Specs, Structure, Pointers, Bio, Website Brief)
 * VOIR Feature Naming Docket.docx (locked names + taglines only)
 * Bi-fold catalogue (promises, EMI, free installation, series cards)
 */
window.VOIR = {
  brand: {
    name: "VOIR",
    tagline: "SEE IT. LOVE IT. LIVE IT.",
    company: "VOIR Appliances Private Limited",
    website: "www.voir.co.in",
    websiteUrl: "https://www.voir.co.in",
  },

  contacts: {
    email: "support@voir.co.in",
    phone: "+91 87408 16000",
    phoneHref: "tel:+918740816000",
    serviceForm:
      "https://docs.google.com/forms/d/1-rl8pdd3Cd1hJffZR9XPvn1MzcyXANATENd_99oelKY/viewform",
    businessEmail: "business@voir.co.in",
  },

  social: {
    instagram: "https://www.instagram.com/voir.global/",
    facebook: "https://www.facebook.com/search/top?q=voirglobal",
  },

  nav: [
    { href: "index.html", label: "Home", id: "home" },
    { href: "tvs.html", label: "Product", id: "tvs" },
    { href: "innovation.html", label: "Innovation", id: "innovation" },
    { href: "support.html", label: "Support", id: "support" },
    { href: "contact.html", label: "Contact Us", id: "contact" },
  ],

  features: [
    { id: "quartz", name: "QUARTZ", tagline: "Zero visible dots. Full colour, exactly as it should be.", group: "Zero-dot panel, wide colour gamut" },
    { id: "swiftmind", name: "SwiftMind", tagline: "Think faster, load quicker, run smoother.", group: "CPU" },
    { id: "truehue", name: "TrueHue", tagline: "Processing every pixel in true-to-life colour.", group: "GPU" },
    { id: "optiram", name: "OptiRAM", tagline: "Fast today, fast always.", group: "Auto cache clearing" },
    { id: "palette", name: "Palette AI Suite", tagline: "Painted in perfect colour.", group: "Picture-quality suite (umbrella)" },
    { id: "huesense", name: "HueSense", tagline: "The one friend who always tells you which shirt actually matches.", group: "Colour Enhancer" },
    { id: "glowsense", name: "GlowSense", tagline: "The lighting director you never had to hire.", group: "AI Brightness Enhancer" },
    { id: "depthsense", name: "DepthSense", tagline: "Makes flat pictures grow a third dimension.", group: "AI Contrast Enhancer" },
    { id: "detailsense", name: "DetailSense", tagline: "Notices things so small, even the camera crew missed them.", group: "AI Sharpness Enhancer" },
    { id: "framesense", name: "FrameSense", tagline: "Keeps pace with the action so you don't get left behind.", group: "AI Motion Enhancer" },
    { id: "clearsense", name: "ClearSense", tagline: "Makes murky scenes confess everything.", group: "AI Clarity Enhancer" },
    { id: "soundstage", name: "Soundstage 3D", tagline: "Sound that moves around you, not just at you.", group: "3D surround sound" },
    { id: "harmony", name: "Harmony AI Suite", tagline: "The invisible sound crew that never asks for a raise.", group: "Audio enhancer suite (umbrella)" },
    { id: "deeppulse", name: "DeepPulse", tagline: "Bass you feel, not just hear.", group: "AI Bass Booster" },
    { id: "soniclift", name: "SonicLift", tagline: "Lifts every sound so nothing gets lost in the mix.", group: "AI Sound Booster" },
    { id: "voicecrisp", name: "VoiceCrisp", tagline: "Keeps dialogue crisp and clear, even over loud scenes.", group: "AI ClearVoice" },
    { id: "voios", name: "VoiOS", tagline: "A TV that knows you better.", group: "Smart OS" },
    { id: "watchanything", name: "WatchAnything", tagline: "Every app. Every show. One place to Watch Anything.", group: "Content discovery + live channels" },
    { id: "airshare", name: "AirShare", tagline: "Why look down when you can AirShare it up? Bigger screen, same moment.", group: "Phone casting" },
    { id: "smarttap", name: "SmartTap", tagline: "Your phone. Your remote. One SmartTap away.", group: "Phone remote control" },
    { id: "homesync", name: "HomeSync", tagline: "One screen. Every device. VOIR HomeSync puts your whole smart home at your fingertips.", group: "IoT device connectivity" },
    { id: "apphub", name: "AppHub", tagline: "Every app you love, right on your TV. Explore VOIR AppHub.", group: "App store" },
    { id: "infinity", name: "Infinity Design", tagline: "Barely-there bezels, so the picture is all you see.", group: "3-side bezel-less design" },
    { id: "surehold", name: "SureHold", tagline: "Built for hands, tested by fidgeters.", group: "Easy-grip remote" },
    { id: "findr", name: "FindR", tagline: "One press, and the remote sings.", group: "Find-my-remote" },
    { id: "kwikeys", name: "KwiKeys", tagline: "Shortcuts so short, they barely count as effort.", group: "3 customizable hotkeys" },
  ],

  pointers: [
    {
      group: "Picture",
      items: [
        { title: "QLED vs Non-QLED (True Colour)", text: "QLED TVs deliver brighter, more vibrant and true-to-life colours compared to regular LED TVs." },
        { title: "Brightness", text: "Higher brightness ensures clear picture even in well-lit rooms." },
        { title: "Contrast", text: "Better contrast means deeper blacks and brighter whites for more depth in visuals." },
        { title: "Sharpness", text: "Sharpness enhances fine details, making images look crisp and clear." },
        { title: "Colours", text: "Rich and accurate colours make everything look more natural and lifelike." },
        { title: "HDR10 / 4K Upscaling", text: "HDR improves picture quality with better light and colour, while 4K upscaling enhances lower-quality content to near-4K clarity." },
      ],
    },
    {
      group: "Sound",
      items: [
        { title: "Bass Effect", text: "Enhanced bass delivers deeper and more powerful sound." },
        { title: "Distortion-Free Sound", text: "Clear audio even at high volume without cracking or noise." },
        { title: "Cinematic (3D Surround Sound)", text: "Immersive sound experience that feels like you’re inside the scene." },
        { title: "Dolby Audio / Dolby Atmos / Dolby Vision", text: "Dolby Audio gives clear sound, Atmos adds surround experience, and Vision enhances picture to look more real." },
      ],
    },
    {
      group: "Processor",
      items: [
        { title: "Faster Performance", text: "Ensures smooth navigation with no lag or buffering." },
        { title: "Powerful Processor", text: "Improves overall picture, sound, and TV performance." },
        { title: "AI Auto Adjustment", text: "Automatically optimizes picture and sound based on content." },
      ],
    },
    {
      group: "Smart Features",
      items: [
        { title: "OTT Experience", text: "Access apps like Netflix, Prime Video, and YouTube directly on TV." },
        { title: "Live Channels (No Set-Top Box)", text: "Watch live TV channels using internet, no cable connection needed." },
        { title: "Screen Mirroring", text: "Cast your mobile screen directly onto the TV." },
        { title: "Voice Search", text: "Search content using voice commands instead of typing." },
        { title: "Watchlist Creation", text: "Save your favorite shows and movies to watch later." },
      ],
    },
    {
      group: "IoT Ready (Selected Models)",
      items: [
        { title: "Smart Home Connectivity", text: "Control and connect your TV with other smart devices at home." },
      ],
    },
    {
      group: "Panel",
      items: [
        { title: "Pixel Pure Panel", text: "Advanced panel technology for clearer and more detailed visuals." },
        { title: "Wide Viewing Angle", text: "Enjoy clear picture from any angle in the room." },
        { title: "Long Lasting", text: "Durable panel designed for long-term performance." },
        { title: "Anti-Glare", text: "Reduces screen reflection for comfortable viewing." },
        { title: "Low Blue Light", text: "Reduces eye strain for safer long viewing hours." },
      ],
    },
    {
      group: "Aesthetics",
      items: [
        { title: "Edge-less Design (Infinity View)", text: "Sleek design with ultra-thin borders for a bigger viewing experience." },
        { title: "Ergonomic Remote", text: "User-friendly remote designed for easy and comfortable control." },
      ],
    },
  ],

  catalogue: {
    promise:
      "We say only what the product can deliver, and we hold that promise long after the sale — parts stocked before launch, a support line a person answers, and an engineer who shows up.",
    threePromisesTitle: "THREE PROMISES, ONE TELEVISION",
    pillars: [
      {
        title: "See it.",
        icon: "eye",
        tagline: "True to life. In every detail.",
        text: "Every VOIR is QLED. Quantum-dot colour stays true at full brightness, contrast holds in a sunlit room, and the picture ages far better than plain LED.",
        items: [
          { icon: "palette", name: "Quantum Color Optimizer", text: "Wider gamut, tuned per scene so colour reads true, not loud." },
          { icon: "display", name: "Infinity Display", text: "Edgeless bezel — the room reads the picture, not the frame." },
          { icon: "panel", name: "Pixel Pure Panel", text: "Every panel graded for uniformity, HD through 4K UHD." },
          { icon: "chip", name: "PQX Pro Elite Suite", text: "A stack of picture technologies working together for a richer, sharper image." },
        ],
      },
      {
        title: "Love it.",
        icon: "speaker",
        tagline: "Sound that moves you.",
        text: "Cinema-grade sound and picture, tuned to work together — immersive audio that fills the room and still feels intimate.",
        items: [
          { icon: "dolby", name: "Dolby Atmos Vision", text: "Cinema-grade picture and sound, tuned to work together." },
          { icon: "waves", name: "Sound Spectre Power Boost", text: "Richer bass, sharper highs, fuller sound across the room." },
          { icon: "sliders", name: "AI Scene Tuning", text: "Picture and sound adapt to what you're watching, automatically." },
          { icon: "mic", name: "VoiceCrisp", text: "Dialogue stays clear even when the action gets loud." },
        ],
      },
      {
        title: "Live it.",
        icon: "home",
        tagline: "A TV for everyday life.",
        text: "Living with a TV is different from owning one. It should wake up fast, put something on before you have finished sitting down, and still feel quick years into its life.",
        items: [
          { icon: "phone", name: "SmartTap", text: "Cast from your phone in a tap, over Wi-Fi or Bluetooth." },
          { icon: "homesync", name: "HomeSync", text: "One screen. Every device. Your whole smart home at your fingertips." },
          { icon: "assistant", name: "Google Assistant", text: "Hold the voice remote and just ask — search, switch inputs, open an app." },
          { icon: "service", name: "Service & Parts", text: "A person on the line, an engineer who shows up, spares stocked before launch." },
        ],
      },
    ],
    closingLine: "The best brands aren't the loudest. They're the ones that keep showing up.",
    emiNote:
      "Free installation applies to all models in Core Series of 40 inch and above, and on all models in Zenith Series. EMI amounts are indicative starting values, subject to approval by financing partners and the applicable tenure.",
    freeInstallBox: {
      title: "Free installation. EMI from ₹1,499 / month.",
      text: "Installation and wall-mount fitting are included in selective models only. EMI plans start at the tenure your financing partner approves.",
    },
    emiTable: [
      { model: "VR32FLG12KQ", emi: "₹1,499/-" },
      { model: "VTQ40CH2EB", emi: "₹1,499/-" },
      { model: "VTQ43CH2EB", emi: "₹1,799/-" },
      { model: "VTN55CH2EB", emi: "₹2,999/-" },
      { model: "VR55FLG14KQ", emi: "₹3,499/-" },
    ],
    sizesLine: "32\" · 40\" · 43\" · 55\" · 65\" | Google TV · Cloud TV",
  },

  about: {
    manifestoEyebrow: "Brand manifesto",
    heritage: "Brand heritage since 2008  |  Incorporated 2023",
    /* VOIR Storyline.docx — Brand Manifesto */
    storyline: [
      "Before there was a name, there were three men who had never met — each standing in a different corner of the same broken promise.",
      "One had lived inside the moment of seeing.",
      "Retail side of the counter. Family business, small-format store, the kind of place that lives or dies on repeat customers. He watched people walk in with their eyes lit up — caught by a glossy box, a confident pitch, a promise that looked good enough to believe. That was the moment a customer saw something and decided to trust it. And he watched, again and again, what happened when that moment of seeing turned out to be staged — when the promise was never fully true to begin with. The customer came back weeks later, angry, holding a product that hadn't been what it appeared to be. The anger was fair. It just kept landing on the wrong person — the one who'd only ever sold what he'd been shown.",
      "Another had lived inside the moment of loving — of a customer choosing to stay.",
      "Years inside distribution, the part of the business customers never see, but the part that quietly decides whether a customer's trust is honoured or spent. He thought often about what it actually feels like to love a brand — the small, repeated reassurance of things arriving when promised, working as promised, someone picking up when you call. That's what loving something really runs on: not the first impression, but the follow-through that no one photographs. And he watched customers give that trust freely, only to have it chipped away by things they never saw and never caused — a spare part that never showed up when the product needed servicing, a warranty claim that went back and forth for weeks with no resolution, a support line that went quiet exactly when it was needed most. The customer didn't stop loving the brand because they wanted to. They stopped because nobody on the other end kept giving them a reason to.",
      "And the third had lived inside the moment of living it — the long haul, after the sale.",
      "As an OEM supplier working closely with the marketing and quality teams of several brands, he didn't just witness the failures — he sat in the rooms where they were quietly written into being, long before a single unit ever reached a shelf. He watched specifications get shaved down from what was once proposed, syllable by syllable, until what remained was only ever a rumour of what the product could have been — the difference pocketed as margin nobody outside that room would ever see. He watched marketing turn possibility into certainty on paper, crafting claims the product was never built to carry, each word chosen with full knowledge of the weight it couldn't bear. He watched service become a line item to be trimmed rather than a promise to be honoured — budgeted thin before the first complaint had even been imagined. Profitability wasn't a compromise that crept in with time. It was the opening line of the story, written before the customer's chapter had even begun — so that the person who eventually paid for the product was, without knowing it, living out a decision already made about them, not for them, in a room they would never enter.",
      "Three different corners. One repeating story, told from three angles — but always ending the same way: a customer, holding a product that didn't live up to what they were told, with nowhere left to take the problem.",
      "By the time the three of them actually sat in the same room, they weren't comparing a business opportunity. They were comparing the same face they'd each seen from a different side of the counter — someone who'd spent hard-earned money trusting a promise that was never fully meant to be kept.",
      "That was the moment something shifted. Not a strategy meeting. A reckoning.",
      "Because to fix it, they realised, you first had to be willing to see the customer — fully, honestly, without the comfortable distance most businesses keep. Not a segment. Not a transaction. A person who had worked hard for their money and simply wanted the promise made to them to be kept.",
      "So they went looking for a word that meant exactly that. Not a promise. Not a pitch. Just the act itself — clear-eyed, honest, unable to look away.",
      "They found it in VOIR. From that single word, the rest followed. It is not just about products. It is everything about the discipline they were committing to: see the customer fully, see the business fully, see the gap between promise and delivery — and refuse to look away from it the way everyone before them had.",
      "See it. Seeing is where every real relationship with a product begins, and almost nobody was building for that moment on purpose. We thought that was strange, for things that end up sitting at the centre of a home. So we started with the part everyone else skips. Make it worth seeing first.",
      "Love it. Love is not a feeling you announce, just one you stop questioning. Not just on day one, but on the hundredth ordinary evening after. So we built products to earn your trust in the weeks after the sale — and if something ever does go wrong, a service call that's actually answered, by someone who actually shows up.",
      "Live it. Living is an experience different from owning it. Experience is not a feature we add on top. It's the only thing we're actually selling.",
      "VOIR wasn't born in a boardroom chasing a market opportunity. It was born from three people who'd each watched the same customer get let down, from three different sides of the same broken chain — and decided the only way forward was to finally see the whole thing, together, and build something that wouldn't repeat it.",
      "That's why the name isn't a flourish. It's a debt being paid.",
      "See it. Love it. Live it.",
      "VOIR.",
    ],
    aboutUs: [
      "VOIR was born in 2008 with a simple belief: smart technology shouldn't be a privilege — it should be within everyone's reach. What started as a promise to deliver honest, feature-rich electronics at accessible prices has grown into a brand trusted by households across the country.",
      "In 2023, that promise was formalized and scaled. VOIR Appliances Private Limited was incorporated by three industry leaders with decades of combined experience in distribution, manufacturing, and consumer electronics — bringing the structure, reach, and ambition needed to take VOIR into its next chapter.",
      "Today, VOIR stands for more than just competitive pricing. We build products around real customer needs, back every purchase with quality service long after the sale, and treat the ownership experience as seriously as the product itself. It's this philosophy — quality without compromise, value without shortcuts — that continues to define us as we grow from a value-for-money favorite into a genuinely premium, technology-led brand.",
    ],
    mission:
      "At VOIR, we exist to close the gap between what a customer is promised and what a customer receives. A brand that a customer never has to defend themselves against — one where seeing it, loving it, and living it are, finally, the same honest experience.",
    vision:
      "To be a technology brand society trust without having to think twice – where every device we make becomes something people don’t just own, but genuinely live with.",
    values: [
      {
        title: "Consumer Centric",
        text: "See the customer fully. A person who had worked hard for their money and simply wanted the promise made to them to be kept.",
      },
      {
        title: "Innovative",
        text: "Smart-technology-first products — Android and Google OS-powered QLED Smart TVs — built around real customer needs.",
      },
      {
        title: "Technology Driven",
        text: "Each new product is a deliberate step using technology as the lever — rather than price alone — to build long-term brand equity.",
      },
    ],
    lifestyleNote: "Currently TVs. More categories will be added later.",
  },

  team: [
    {
      name: "Mr. Gandharv Daga",
      role: "Key Leader",
      org: "Touchstone Group",
      title: "Key Leader — Touchstone Group",
      focus: "Telecom · Consumer Electronics · Financial Services",
      initials: "GD",
      paragraphs: [
        "Mr. Gandharv Daga is a seasoned entrepreneur with over 14+ years of experience across Telecom, Consumer Electronics, and Financial Services. As a key leader at Touchstone Group—one of the region’s leading distribution networks, representing top national and global brands with a strong market presence and significant turnover—he spearheads telecom and consumer electronics operations, driving sustainable growth, operational excellence, and market expansion.",
        "He has a proven track record of delivering innovative sell-out growth strategies, enabling consistent business performance in competitive markets. Backed by his expertise in investments and financial planning, he brings a strategic and scalable approach to business building.",
        "Mr. Daga is widely recognized for cultivating strong partner ecosystems and client relationships, making him a key contributor to long-term business success.",
      ],
    },
    {
      name: "Mr. Mohit Goyal",
      role: "Core Leader",
      org: "Voir India Electronics Private Limited",
      title: "Core Leader — Voir India Electronics",
      focus: "Operations · Manufacturing · Brand Building",
      initials: "MG",
      paragraphs: [
        "Mr. Mohit Goyal is an accomplished entrepreneur and business strategist with over 15+ years of experience spanning consumer electronics, manufacturing, and business development. As a core leader at Voir India Electronics Private Limited, he has played a pivotal role in establishing and expanding the organization, driving high-impact growth and operational transformation.",
        "He has a proven track record in profit centre operations, go-to-market strategy, and brand building, with the ability to identify untapped opportunities and convert them into scalable business outcomes. His expertise extends across product innovation, manufacturing processes, and sales strategy, enabling end-to-end business leadership.",
        "Recognized for his entrepreneurial mindset and strong execution capabilities, Mr. Goyal excels at building high-performing teams, forging strategic partnerships, and delivering sustained business growth in competitive markets.",
      ],
    },
    {
      name: "Mr. Tarun Kalani",
      role: "Business Leader",
      org: "Surya Marketing",
      title: "Business Leader — Surya Marketing",
      focus: "Distribution · Market Development · Rural Growth",
      initials: "TK",
      paragraphs: [
        "Mr. Tarun Kalani is an entrepreneur and business leader in the consumer electronics and home appliances industry, currently driving growth at Surya Marketing, one of Rajasthan’s leading and most established distribution houses with a strong presence across all 33 districts and 500+ towns and villages.",
        "He brings strong expertise in B2B distribution, dealer network expansion, and market development, with a sharp focus on rural and emerging markets. His approach centers on building scalable, system-driven frameworks that enable consistent and sustainable growth.",
        "At Surya Marketing, he is playing a key role in strengthening a legacy distribution network known for its long-standing partnerships with leading national and global brands, while driving modernization through digital tools and structured sales systems.",
        "Known for blending traditional trade relationships with modern systems, Mr. Kalani is focused on creating efficient distribution ecosystems that enhance visibility, simplify operations, and unlock new growth opportunities.",
      ],
    },
  ],

  series: {
    core: {
      id: "core",
      name: "Core Series",
      osLine: "CLOUD TV",
      accent: "orange",
      panel: "QLED",
    },
    zenith: {
      id: "zenith",
      name: "Zenith Series",
      osLine: "GOOGLE TV",
      accent: "orange",
      panel: "QLED",
    },
    vantage: {
      id: "vantage",
      name: "Vantage Series",
      osLine: "COMING SOON",
      accent: "orange",
      panel: "QLED",
      comingSoon: true,
    },
  },

  models: [],
};

(function () {
  const keyG = [
    "AI Quantum Core Processor",
    "Google TV - Google Assistant, Google Chromecast, Easy Access to More than 1000 Apps, Build Your Watchlist, Virtual Remote",
    "OTT Apps",
    "Dolby Vision.Atmos",
    "HDR10",
    "4K Upscalling",
    "Live Color Booster",
    "Dynamic Picture Optimiser",
    "Edgeless Design",
    "Ergonomic Remote",
  ];
  const keyC = [
    "Processor",
    "Pixel Pure Panel",
    "Google TV - Google Assistant, Google Chromecast, Easy Access to More than 1000 Apps, Build Your Watchlist, Virtual Remote",
    "OTT Apps",
    "Dolby Audio",
    "HDR10",
    "Live Color Booster",
    "Dynamic Picture Optimiser",
    "Edgeless Design",
    "Ergonomic Remote",
  ];
  const keyAdditional = [
    "Pixel Pure Panel",
    "Quantum Core Processor",
    "OTT Apps",
    "100+ Live Free Channels and Movies",
    "Screen Mirroring",
    "Live Color Booster",
    "Dynamic Picture Optimiser",
    "3D Surround Sound",
    "Edgeless Design",
    "Ergonomic Remote",
  ];

  function spec(groups) {
    return groups;
  }

  const appsGC = "Netflix, Prime Video, JioHotstar, YouTube, Google Play, FastCast, Smart Player";
  const appsAdd = "Prime Video, JioHotstar, YouTube, Sony Live, Zee5";

  window.VOIR.models = [
    {
      id: "VR32FLG12KQ",
      series: "zenith",
      size: '32"',
      qled: true,
      resolution: "1366*768",
      resolutionLabel: "HD",
      os: "Google TV",
      image: "images/zenith-32.jpg",
      processor: "Quantam Core Ai Processor",
      peakBrightness: "325 nits",
      ramStorage: "1.5GB + 8GB",
      panelType: "Pixel Pure Panel",
      keyFeatures: keyG,
      emi: "₹1,499/-",
      freeInstallation: true,
      specs: spec({
        Display: [
          ["Colours", "1.07 Billion QLED"],
          ["Resolution", "1366*768"],
          ["Panel Type", "Pixel Pure Panel"],
          ["Bezel Design", "Infinity Design"],
          ["HDR Compatibility", "HDR10"],
          ["Peak Brightness", "325 nits"],
          ["Colour Gamut", "Yes"],
          ["Digital Noise Reduction", "Yes"],
          ["Intelligent Frame Stabilization Engine", "Yes"],
          ["Micro Dimming", "Yes"],
          ["Dolby Vision", "NA"],
          ["AI Contrast Enhancer", "Yes"],
          ["AI Motion Enhancer", "Yes"],
          ["Live Color & Clarity Enhancer", "Yes"],
        ],
        Sound: [
          ["Dolby Audio Format", "Dolby Digital Plus"],
          ["Thunderwave Surround Sound", "Yes"],
          ["Sound Balance & Sound Reset", "Yes"],
        ],
        Features: [
          ["OS", "Google TV"],
          ["Voice Assistant", "Yes"],
          ["WiFi", "Dual Band WiFi 2.4GHz + 5GHz"],
          ["Casting", "Built-in Chromecast"],
          ["Bluetooth", "2 way Bluetooth"],
          ["Pre Installed Applications", appsGC],
        ],
        Hardware: [
          ["Processor", "Quantam Core Ai Processor"],
          ["USB", "USB2.0 X 2"],
          ["HDMI", "HDMI 1.4 X 3"],
          ["RAM & Storage", "1.5GB + 8GB"],
          ["GPU", "Quad core, 1.5GHz"],
          ["CPU", "Mali G31"],
        ],
        "Smart Features": [
          ["Voice Assistant", "Yes"],
          ["Virtual Remote", "Yes"],
          ["Smart Home Ready", "Yes"],
          ["Remote Name", "Eco Remote"],
        ],
        Additional: [
          ["Sound", "CineSound Experience"],
          ["Audio Bass", "Sonic Boom"],
          ["Speakers", ""],
          ["Picture", "PQx Pro"],
          ["Processor", "HyperNex AI"],
        ],
      }),
    },
    {
      id: "VR43FLG12KQ",
      series: "zenith",
      size: '43"',
      qled: true,
      resolution: "1920*1080",
      resolutionLabel: "FHD",
      os: "Google TV",
      image: "images/core-43.jpg",
      processor: "Quantam Core Ai Processor",
      peakBrightness: "325 nits",
      ramStorage: "1.5GB + 8GB",
      panelType: "Pixel Pure Panel",
      keyFeatures: keyG,
      emi: "₹1,499/-",
      freeInstallation: true,
      specs: spec({
        Display: [
          ["Colours", "1.07 Billion QLED"],
          ["Resolution", "1920*1080"],
          ["Panel Type", "Pixel Pure Panel"],
          ["Bezel Design", "Infinity Design"],
          ["HDR Compatibility", "HDR10"],
          ["Peak Brightness", "325 nits"],
          ["Colour Gamut", "Yes"],
          ["Digital Noise Reduction", "Yes"],
          ["Intelligent Frame Stabilization Engine", "Yes"],
          ["Micro Dimming", "Yes"],
          ["Dolby Vision", "NA"],
          ["AI Contrast Enhancer", "Yes"],
          ["AI Motion Enhancer", "Yes"],
          ["Live Color & Clarity Enhancer", "Yes"],
        ],
        Sound: [
          ["Dolby Audio Format", "Dolby Digital Plus"],
          ["Thunderwave Surround Sound", "Yes"],
          ["Sound Balance & Sound Reset", "Yes"],
        ],
        Features: [
          ["OS", "Google TV"],
          ["Voice Assistant", "Yes"],
          ["WiFi", "Dual Band WiFi 2.4GHz + 5GHz"],
          ["Casting", "Built-in Chromecast"],
          ["Bluetooth", "2 way Bluetooth"],
          ["Pre Installed Applications", appsGC],
        ],
        Hardware: [
          ["Processor", "Quantam Core Ai Processor"],
          ["USB", "USB2.0 X 2"],
          ["HDMI", "HDMI 1.4 X 3"],
          ["RAM & Storage", "1.5GB + 8GB"],
          ["GPU", "Quad core, 1.5GHz"],
          ["CPU", "Mali G31"],
        ],
        "Smart Features": [
          ["Voice Assistant", "Yes"],
          ["Virtual Remote", "Yes"],
          ["Smart Home Ready", "Yes"],
          ["Remote Name", "Eco Remote"],
        ],
        Additional: [
          ["Sound", "CineSound Experience"],
          ["Audio Bass", "Sonic Boom"],
          ["Speakers", ""],
          ["Picture", "PQx Pro"],
          ["Processor", "HyperNex AI"],
        ],
      }),
    },
    {
      id: "VR55FLG14KQ",
      series: "zenith",
      size: '55"',
      qled: true,
      resolution: "3840*2160",
      resolutionLabel: "UHD",
      os: "Google TV",
      image: "images/zenith-55.jpg",
      processor: "Quantam Core Ai Processor",
      peakBrightness: "325 nits",
      ramStorage: "2GB + 16GB",
      panelType: "Pixel Pure Panel",
      keyFeatures: keyG,
      emi: "₹3,499/-",
      freeInstallation: true,
      specs: spec({
        Display: [
          ["Colours", "1.07 Billion QLED"],
          ["Resolution", "3840*2160"],
          ["Panel Type", "Pixel Pure Panel"],
          ["Bezel Design", "Infinity Design"],
          ["HDR Compatibility", "HDR10"],
          ["Peak Brightness", "325 nits"],
          ["Colour Gamut", "Yes"],
          ["Digital Noise Reduction", "Yes"],
          ["Intelligent Frame Stabilization Engine", "Yes"],
          ["Micro Dimming", "Yes"],
          ["Dolby Vision", "Yes"],
          ["AI Contrast Enhancer", "Yes"],
          ["AI Motion Enhancer", "Yes"],
          ["Live Color & Clarity Enhancer", "Yes"],
        ],
        Sound: [
          ["Dolby Audio Format", "Dolby Atmos"],
          ["Thunderwave Surround Sound", "Yes"],
          ["Sound Balance & Sound Reset", "Yes"],
        ],
        Features: [
          ["OS", "Google TV"],
          ["Voice Assistant", "Yes"],
          ["WiFi", "Dual Band WiFi 2.4GHz + 5GHz"],
          ["Casting", "Built-in Chromecast"],
          ["Bluetooth", "2 way Bluetooth"],
          ["Pre Installed Applications", appsGC],
        ],
        Hardware: [
          ["Processor", "Quantam Core Ai Processor"],
          ["USB", "USB2.0 X 2"],
          ["HDMI", "HDMI 2.0 X 3"],
          ["RAM & Storage", "2GB + 16GB"],
          ["GPU", "Quad core, 1.5GHz"],
          ["CPU", "Mali G52"],
        ],
        "Smart Features": [
          ["Voice Assistant", "Yes"],
          ["Virtual Remote", "Yes"],
          ["Smart Home Ready", "Yes"],
          ["Remote Name", "Eco Remote"],
        ],
        Additional: [
          ["Sound", "CineSound Experience"],
          ["Audio Bass", "Sonic Boom"],
          ["Speakers", ""],
          ["Picture", "PQx Pro"],
          ["Processor", "HyperNex AI"],
        ],
      }),
    },
    {
      id: "VR65FLG14KQ",
      series: "zenith",
      size: '65"',
      qled: true,
      resolution: "3840*2160",
      resolutionLabel: "UHD",
      os: "Google TV",
      image: "images/zenith-65.jpg",
      processor: "Quantam Core Ai Processor",
      peakBrightness: "325 nits",
      ramStorage: "2GB + 16GB",
      panelType: "Pixel Pure Panel",
      keyFeatures: keyG,
      freeInstallation: true,
      specs: spec({
        Display: [
          ["Colours", "1.07 Billion QLED"],
          ["Resolution", "3840*2160"],
          ["Panel Type", "Pixel Pure Panel"],
          ["Bezel Design", "Infinity Design"],
          ["HDR Compatibility", "HDR10"],
          ["Peak Brightness", "325 nits"],
          ["Colour Gamut", "Yes"],
          ["Digital Noise Reduction", "Yes"],
          ["Intelligent Frame Stabilization Engine", "Yes"],
          ["Micro Dimming", "Yes"],
          ["Dolby Vision", "Yes"],
          ["AI Contrast Enhancer", "Yes"],
          ["AI Motion Enhancer", "Yes"],
          ["Live Color & Clarity Enhancer", "Yes"],
        ],
        Sound: [
          ["Dolby Audio Format", "Dolby Atmos"],
          ["Thunderwave Surround Sound", "Yes"],
          ["Sound Balance & Sound Reset", "Yes"],
        ],
        Features: [
          ["OS", "Google TV"],
          ["Voice Assistant", "Yes"],
          ["WiFi", "Dual Band WiFi 2.4GHz + 5GHz"],
          ["Casting", "Built-in Chromecast"],
          ["Bluetooth", "2 way Bluetooth"],
          ["Pre Installed Applications", appsGC],
        ],
        Hardware: [
          ["Processor", "Quantam Core Ai Processor"],
          ["USB", "USB2.0 X 2"],
          ["HDMI", "HDMI 2.0 X 3"],
          ["RAM & Storage", "2GB + 16GB"],
          ["GPU", "Quad core, 1.5GHz"],
          ["CPU", "Mali G52"],
        ],
        "Smart Features": [
          ["Voice Assistant", "Yes"],
          ["Virtual Remote", "Yes"],
          ["Smart Home Ready", "Yes"],
          ["Remote Name", "Eco Remote"],
        ],
        Additional: [
          ["Sound", "CineSound Experience"],
          ["Audio Bass", "Sonic Boom"],
          ["Speakers", ""],
          ["Picture", "PQx Pro"],
          ["Processor", "HyperNex AI"],
        ],
      }),
    },
    {
      id: "VTN32CH2EB",
      series: "core",
      size: '32"',
      qled: true,
      resolution: "1366*768",
      resolutionLabel: "HD",
      os: "Cloud TV, Android 14",
      image: "images/core-32.jpg",
      processor: "Quantum Core Processor",
      peakBrightness: "250 nits",
      ramStorage: "512 MB + 4 GB",
      panelType: "Pixel Pure Panel",
      keyFeatures: keyAdditional,
      specs: spec({
        Display: [
          ["Colours", "16.7 Million QLED"],
          ["Resolution", "1366*768"],
          ["Panel Type", "Pixel Pure Panel"],
          ["Bezel Design", "Infinity Design"],
          ["Selectable Picture Modes", "7"],
          ["Peak Brightness", "250 nits"],
          ["Aspect Ratio", "16:9"],
          ["Digital Noise Reduction", "Yes"],
          ["Zoom Mode", "Yes"],
          ["Micro Dimming", "Yes"],
          ["Dolby Vision", "NA"],
          ["Dynamic Picture Optimizer", "Yes"],
          ["Live Color Booster", "Yes"],
        ],
        Sound: [
          ["Selectable Sound Modes", "7"],
          ["3D Surround Sound", "Yes"],
          ["Sound Balance & Sound Reset", "Yes"],
        ],
        Features: [
          ["OS", "Cloud TV, Android 14"],
          ["WiFi", "Yes"],
          ["Screen Casting", "Yes"],
          ["Bluetooth", "NA"],
          ["Pre Installed Applications", appsAdd],
        ],
        Hardware: [
          ["Processor", "Quad Core Processor"],
          ["USB", "USB2.0 X 2"],
          ["HDMI", "HDMI 1.4 X 2"],
          ["RAM & Storage", "512 MB + 4 GB"],
          ["GPU", "Quad core, 1.5GHz"],
          ["CPU", "Mali G31"],
        ],
        "Smart Features": [
          ["Free Channels", "100+ Live TV Channel Access"],
          ["Free Movies", "10,000+ free movies, documentaries, and short films"],
          ["Universal Search", "Yes"],
          ["Remote Name", "Arc Remote"],
        ],
        Additional: [
          ["Sound", "CineSound Experience"],
          ["Audio", "Sonic Boom"],
          ["Picture", "PQx Core"],
          ["Processor", "Quantum Core Processor"],
        ],
      }),
    },
    {
      id: "VTQ32CH2EB",
      series: "core",
      size: '32"',
      qled: true,
      resolution: "1366*768",
      resolutionLabel: "HD",
      os: "Cloud TV, Android 14",
      image: "images/core-32.jpg",
      processor: "Quantum Core Processor",
      peakBrightness: "250 nits",
      ramStorage: "1 GB + 8 GB",
      panelType: "Pixel Pure Panel",
      keyFeatures: keyAdditional,
      specs: spec({
        Display: [
          ["Colours", "16.7 Million QLED"],
          ["Resolution", "1366*768"],
          ["Panel Type", "Pixel Pure Panel"],
          ["Bezel Design", "Infinity Design"],
          ["Selectable Picture Modes", "7"],
          ["Peak Brightness", "250 nits"],
          ["Aspect Ratio", "16:9"],
          ["Digital Noise Reduction", "Yes"],
          ["Zoom Mode", "Yes"],
          ["Micro Dimming", "Yes"],
          ["Dolby Vision", "NA"],
          ["Dynamic Picture Optimizer", "Yes"],
          ["Live Color Booster", "Yes"],
        ],
        Sound: [
          ["Selectable Sound Modes", "7"],
          ["3D Surround Sound", "Yes"],
          ["Sound Balance & Sound Reset", "Yes"],
        ],
        Features: [
          ["OS", "Cloud TV, Android 14"],
          ["WiFi", "Yes"],
          ["Screen Casting", "Yes"],
          ["Bluetooth", "NA"],
          ["Pre Installed Applications", appsAdd],
        ],
        Hardware: [
          ["Processor", "Quad Core Processor"],
          ["USB", "USB2.0 X 2"],
          ["HDMI", "HDMI 1.4 X 2"],
          ["RAM & Storage", "1 GB + 8 GB"],
          ["GPU", "Quad core, 1.5GHz"],
          ["CPU", "Mali G52"],
        ],
        "Smart Features": [
          ["Free Channels", "100+ Live TV Channel Access"],
          ["Free Movies", "10,000+ free movies, documentaries, and short films"],
          ["Universal Search", "Yes"],
          ["Remote Name", "Arc Remote"],
        ],
        Additional: [
          ["Sound", "CineSound Experience"],
          ["Audio", "Sonic Boom"],
          ["Picture", "PQx Core"],
          ["Processor", "Quantum Core Processor"],
        ],
      }),
    },
    {
      id: "VTQ40CH2EB",
      series: "core",
      size: '40"',
      qled: true,
      resolution: "1920*1080",
      resolutionLabel: "FHD",
      os: "Cloud TV, Android 14",
      image: "images/core-40.jpg",
      processor: "Quantum Core Processor",
      peakBrightness: "300 nits",
      ramStorage: "1 GB + 8 GB",
      panelType: "Pixel Pure Panel",
      keyFeatures: keyAdditional,
      freeInstallation: true,
      specs: spec({
        Display: [
          ["Colours", "16.7 Million QLED"],
          ["Resolution", "1920*1080"],
          ["Panel Type", "Pixel Pure Panel"],
          ["Bezel Design", "Infinity Design"],
          ["Selectable Picture Modes", "7"],
          ["Peak Brightness", "300 nits"],
          ["Aspect Ratio", "16:9"],
          ["Digital Noise Reduction", "Yes"],
          ["Zoom Mode", "Yes"],
          ["Micro Dimming", "Yes"],
          ["Dolby Vision", "NA"],
          ["Dynamic Picture Optimizer", "Yes"],
          ["Live Color Booster", "Yes"],
        ],
        Sound: [
          ["Selectable Sound Modes", "7"],
          ["3D Surround Sound", "Yes"],
          ["Sound Balance & Sound Reset", "Yes"],
        ],
        Features: [
          ["OS", "Cloud TV, Android 14"],
          ["WiFi", "Yes"],
          ["Screen Casting", "Yes"],
          ["Bluetooth", "NA"],
          ["Pre Installed Applications", appsAdd],
        ],
        Hardware: [
          ["Processor", "Quad Core Processor"],
          ["USB", "USB2.0 X 2"],
          ["HDMI", "HDMI 1.4 X 2"],
          ["RAM & Storage", "1 GB + 8 GB"],
          ["GPU", "Quad core, 1.5GHz"],
          ["CPU", "Mali G52"],
        ],
        "Smart Features": [
          ["Free Channels", "100+ Live TV Channel Access"],
          ["Free Movies", "10,000+ free movies, documentaries, and short films"],
          ["Universal Search", "Yes"],
          ["Remote Name", "Arc Remote"],
        ],
        Additional: [
          ["Sound", "CineSound Experience"],
          ["Audio", "Sonic Boom"],
          ["Picture", "PQx Core"],
          ["Processor", "Quantum Core Processor"],
        ],
      }),
    },
    {
      id: "VTQ43CH2EB",
      series: "core",
      size: '43"',
      qled: true,
      resolution: "1920*1080",
      resolutionLabel: "FHD",
      os: "Cloud TV, Android 14",
      image: "images/core-43.jpg",
      processor: "Quantum Core Processor",
      peakBrightness: "300 nits",
      ramStorage: "1 GB + 8 GB",
      panelType: "Pixel Pure Panel",
      keyFeatures: keyAdditional,
      freeInstallation: true,
      specs: spec({
        Display: [
          ["Colours", "16.7 Million QLED"],
          ["Resolution", "1920*1080"],
          ["Panel Type", "Pixel Pure Panel"],
          ["Bezel Design", "Infinity Design"],
          ["Selectable Picture Modes", "7"],
          ["Peak Brightness", "300 nits"],
          ["Aspect Ratio", "16:9"],
          ["Digital Noise Reduction", "Yes"],
          ["Zoom Mode", "Yes"],
          ["Micro Dimming", "Yes"],
          ["Dolby Vision", "NA"],
          ["Dynamic Picture Optimizer", "Yes"],
          ["Live Color Booster", "Yes"],
        ],
        Sound: [
          ["Selectable Sound Modes", "7"],
          ["3D Surround Sound", "Yes"],
          ["Sound Balance & Sound Reset", "Yes"],
        ],
        Features: [
          ["OS", "Cloud TV, Android 14"],
          ["WiFi", "Yes"],
          ["Screen Casting", "Yes"],
          ["Bluetooth", "NA"],
          ["Pre Installed Applications", appsAdd],
        ],
        Hardware: [
          ["Processor", "Quad Core Processor"],
          ["USB", "USB2.0 X 2"],
          ["HDMI", "HDMI 1.4 X 2"],
          ["RAM & Storage", "1 GB + 8 GB"],
          ["GPU", "Quad core, 1.5GHz"],
          ["CPU", "Mali G52"],
        ],
        "Smart Features": [
          ["Free Channels", "100+ Live TV Channel Access"],
          ["Free Movies", "10,000+ free movies, documentaries, and short films"],
          ["Universal Search", "Yes"],
          ["Remote Name", "Arc Remote"],
        ],
        Additional: [
          ["Sound", "CineSound Experience"],
          ["Audio", "Sonic Boom"],
          ["Picture", "PQx Core"],
          ["Processor", "Quantum Core Processor"],
        ],
      }),
    },
    {
      id: "VTN55CH2EB",
      series: "core",
      size: '55"',
      qled: true,
      resolution: "3840*2160",
      resolutionLabel: "UHD",
      os: "Cloud TV, Android 14",
      image: "images/core-55.jpg",
      processor: "Quantum Core Processor",
      peakBrightness: "325 nits",
      ramStorage: "1 GB + 8 GB",
      panelType: "Pixel Pure Panel",
      keyFeatures: keyAdditional,
      freeInstallation: true,
      specs: spec({
        Display: [
          ["Colours", "16.7 Million QLED"],
          ["Resolution", "3840*2160"],
          ["Panel Type", "Pixel Pure Panel"],
          ["Bezel Design", "Infinity Design"],
          ["Selectable Picture Modes", "7"],
          ["Peak Brightness", "325 nits"],
          ["Aspect Ratio", "16:9"],
          ["Digital Noise Reduction", "Yes"],
          ["Zoom Mode", "Yes"],
          ["Micro Dimming", "Yes"],
          ["Dolby Vision", "NA"],
          ["Dynamic Picture Optimizer", "Yes"],
          ["Live Color Booster", "Yes"],
        ],
        Sound: [
          ["Selectable Sound Modes", "7"],
          ["3D Surround Sound", "Yes"],
          ["Sound Balance & Sound Reset", "Yes"],
        ],
        Features: [
          ["OS", "Cloud TV, Android 14"],
          ["WiFi", "Yes"],
          ["Screen Casting", "Yes"],
          ["Bluetooth", "NA"],
          ["Pre Installed Applications", appsAdd],
        ],
        Hardware: [
          ["Processor", "Quad Core Processor"],
          ["USB", "USB2.0 X 2"],
          ["HDMI", "HDMI 1.4 X 2"],
          ["RAM & Storage", "1 GB + 8 GB"],
          ["GPU", "Quad core, 1.5GHz"],
          ["CPU", "Mali G52"],
        ],
        "Smart Features": [
          ["Free Channels", "100+ Live TV Channel Access"],
          ["Free Movies", "10,000+ free movies, documentaries, and short films"],
          ["Universal Search", "Yes"],
          ["Remote Name", "Arc Remote"],
        ],
        Additional: [
          ["Sound", "CineSound Experience"],
          ["Audio", "Sonic Boom"],
          ["Picture", "PQx Core"],
          ["Processor", "Quantum Core Processor"],
        ],
      }),
    },
    {
      id: "VTN65CH2EB",
      series: "core",
      size: '65"',
      qled: true,
      resolution: "3840*2160",
      resolutionLabel: "UHD",
      os: "Cloud TV, Android 14",
      image: "images/zenith-65.jpg",
      processor: "Quantum Core Processor",
      peakBrightness: "325 nits",
      ramStorage: "1 GB + 8 GB",
      panelType: "Pixel Pure Panel",
      keyFeatures: keyAdditional,
      freeInstallation: true,
      specs: spec({
        Display: [
          ["Colours", "16.7 Million QLED"],
          ["Resolution", "3840*2160"],
          ["Panel Type", "Pixel Pure Panel"],
          ["Bezel Design", "Infinity Design"],
          ["Selectable Picture Modes", "7"],
          ["Peak Brightness", "325 nits"],
          ["Aspect Ratio", "16:9"],
          ["Digital Noise Reduction", "Yes"],
          ["Zoom Mode", "Yes"],
          ["Micro Dimming", "Yes"],
          ["Dolby Vision", "NA"],
          ["Dynamic Picture Optimizer", "Yes"],
          ["Live Color Booster", "Yes"],
        ],
        Sound: [
          ["Selectable Sound Modes", "7"],
          ["3D Surround Sound", "Yes"],
          ["Sound Balance & Sound Reset", "Yes"],
        ],
        Features: [
          ["OS", "Cloud TV, Android 14"],
          ["WiFi", "Yes"],
          ["Screen Casting", "Yes"],
          ["Bluetooth", "NA"],
          ["Pre Installed Applications", appsAdd],
        ],
        Hardware: [
          ["Processor", "Quad Core Processor"],
          ["USB", "USB2.0 X 2"],
          ["HDMI", "HDMI 1.4 X 2"],
          ["RAM & Storage", "1 GB + 8 GB"],
          ["GPU", "Quad core, 1.5GHz"],
          ["CPU", "Mali G52"],
        ],
        "Smart Features": [
          ["Free Channels", "100+ Live TV Channel Access"],
          ["Free Movies", "10,000+ free movies, documentaries, and short films"],
          ["Universal Search", "Yes"],
          ["Remote Name", "Arc Remote"],
        ],
        Additional: [
          ["Sound", "CineSound Experience"],
          ["Audio", "Sonic Boom"],
          ["Picture", "PQx Core"],
          ["Processor", "Quantum Core Processor"],
        ],
      }),
    },
  ];

  window.VOIR.getModel = function (id) {
    return window.VOIR.models.find(function (m) {
      return m.id === id;
    });
  };
  window.VOIR.modelsBySeries = function (seriesId) {
    return window.VOIR.models.filter(function (m) {
      return m.series === seriesId;
    });
  };
  window.VOIR.resolveSeriesId = function (raw) {
    var map = {
      zenith: "zenith",
      core: "core",
      vantage: "vantage",
      g: "zenith",
      c: "core",
      additional: "core",
    };
    var key = String(raw || "").replace(/^#/, "").toLowerCase();
    return map[key] || "core";
  };
})();
